/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-12-27 14:41:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/spring/final1/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/final11/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1604883833700L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("    \n");
      out.write("   \n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write(" \n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"description\" content=\"\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n");
      out.write("    <!-- The above 4 meta tags *must* come first in the head; any other head content must come *after* these tags -->\n");
      out.write("\n");
      out.write("    <!-- Title -->\n");
      out.write("    <title>Cafe人 - 카페를 좋아하는 사람들</title>\n");
      out.write("\n");
      out.write("    ");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("    \n");
      out.write("     <link rel=\"icon\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/core-img/favicon2.png.jpg\">\n");
      out.write("\n");
      out.write("    <!-- Stylesheet -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/style.css\">\n");
      out.write("    \n");
      out.write("<script src=\"http://code.jquery.com/jquery-3.1.1.min.js\"></script>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("    <!-- Preloader -->\n");
      out.write("    <div class=\"preloader d-flex align-items-center justify-content-center\">\n");
      out.write("        <div class=\"preloader-content\">\n");
      out.write("            <h3>Welecome Caffe人</h3>\n");
      out.write("            <div id=\"cooking\">\n");
      out.write("                <div class=\"bubble\"></div>\n");
      out.write("                <div class=\"bubble\"></div>\n");
      out.write("                <div class=\"bubble\"></div>\n");
      out.write("                <div class=\"bubble\"></div>\n");
      out.write("                <div class=\"bubble\"></div>\n");
      out.write("                <div id=\"area\">\n");
      out.write("                    <div id=\"sides\">\n");
      out.write("                        <div id=\"pan\"></div>\n");
      out.write("                        <div id=\"handle\"></div>\n");
      out.write("                    </div>\n");
      out.write("                    <div id=\"pancake\">\n");
      out.write("                        <div id=\"pastry\"></div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\n");
      out.write(" \n");
      out.write("    <!-- ##### Treading Post Area Start ##### -->\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "secmenu.jsp", out, false);
      out.write("\n");
      out.write("    <!-- ##### Treading Post Area End ##### -->\n");
      out.write("\n");
      out.write("    <!-- ##### Hero Area Start ##### -->\n");
      out.write("    <div class=\"hero-area\">\n");
      out.write("        <!-- Hero Post Slides -->\n");
      out.write("        <div class=\"hero-post-slides owl-carousel\">\n");
      out.write("            <!-- Single Slide -->\n");
      out.write("      ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <!-- ##### Hero Area End ##### -->\n");
      out.write("\n");
      out.write("    <!-- ##### Catagory Area Start ##### -->\n");
      out.write("   <div class=\"post-catagory section-padding-100-0 mb-70\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row justify-content-center\">\n");
      out.write("                <!-- Single Post Catagory -->\n");
      out.write("                <div class=\"col-12 col-md-6 col-lg-4\">\n");
      out.write("                    <div class=\"single-post-catagory mb-30\">\n");
      out.write("                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/bg-img/4.jpg\" alt=\"\">\n");
      out.write("                        <!-- Content -->\n");
      out.write("                        <div class=\"catagory-content-bg\">\n");
      out.write("                            <div class=\"catagory-content\">\n");
      out.write("                                <a href=\"#\" class=\"post-tag\">The Best</a>\n");
      out.write("                                <a href=\"#\" class=\"post-title\">Healthy Food</a>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <!-- Single Post Catagory -->\n");
      out.write("                <div class=\"col-12 col-md-6 col-lg-4\">\n");
      out.write("                    <div class=\"single-post-catagory mb-30\">\n");
      out.write("                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/bg-img/5.jpg\" alt=\"\">\n");
      out.write("                        <!-- Content -->\n");
      out.write("                        <div class=\"catagory-content-bg\">\n");
      out.write("                            <div class=\"catagory-content\">\n");
      out.write("                                <a href=\"#\" class=\"post-tag\">The Best</a>\n");
      out.write("                                <a href=\"#\" class=\"post-title\">Organic Cuisine</a>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <!-- Single Post Catagory -->\n");
      out.write("                <div class=\"col-12 col-md-6 col-lg-4\">\n");
      out.write("                    <div class=\"single-post-catagory mb-30\">\n");
      out.write("                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/bg-img/6.jpg\" alt=\"\">\n");
      out.write("                        <!-- Content -->\n");
      out.write("                        <div class=\"catagory-content-bg\">\n");
      out.write("                            <div class=\"catagory-content\">\n");
      out.write("                                <a href=\"#\" class=\"post-tag\">The Best</a>\n");
      out.write("                                <a href=\"#\" class=\"post-title\">Vegetarian Food</a>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <!-- ##### Catagory Area End ##### -->\n");
      out.write("\n");
      out.write("    <!-- ##### Big Posts Area Start ##### -->\n");
      out.write("    \n");
      out.write("    \n");
      out.write("    <div class=\"big-posts-area mb-50\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <!-- Single Big Post Area -->\n");
      out.write("             ");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("            <!-- Single Big Post Area -->\n");
      out.write("          \n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <!-- ##### Big Posts Area End ##### -->\n");
      out.write("\n");
      out.write("    <!-- ##### Posts Area End ##### -->\n");
      out.write("    <div class=\"bueno-post-area mb-70\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row justify-content-center\">\n");
      out.write("                <!-- Post Area -->\n");
      out.write("                <div class=\"col-12 col-lg-8 col-xl-9\">\n");
      out.write("                    <!-- Single Blog Post -->\n");
      out.write("                    ");
      if (_jspx_meth_c_005fforEach_005f2(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                   </div>\n");
      out.write("                   \n");
      out.write("                <!-- Sidebar Area -->\n");
      out.write("                <div class=\"col-12 col-sm-9 col-md-6 col-lg-4 col-xl-3\">\n");
      out.write("                    <div class=\"sidebar-area\">\n");
      out.write("\n");
      out.write("                        <!-- Single Widget Area -->\n");
      out.write("                        <div class=\"single-widget-area add-widget mb-30\">\n");
      out.write("                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/bg-img/add.png\" alt=\"\">\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <!-- Single Widget Area -->\n");
      out.write("                        <div class=\"single-widget-area post-widget\">\n");
      out.write("\n");
      out.write("                            <!-- Single Post Area -->\n");
      out.write("                            <div class=\"single-post-area d-flex\">\n");
      out.write("                                <!-- Blog Thumbnail -->\n");
      out.write("                                <div class=\"blog-thumbnail\">\n");
      out.write("                                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/bg-img/12.jpg\" alt=\"\">\n");
      out.write("                                </div>\n");
      out.write("                                <!-- Blog Content -->\n");
      out.write("                                <div class=\"blog-content\">\n");
      out.write("                                    <a href=\"#\" class=\"post-title\">Friend eggs with ham</a>\n");
      out.write("                                    <div class=\"post-meta\">\n");
      out.write("                                        <a href=\"#\" class=\"post-date\">July 11, 2018</a>\n");
      out.write("                                        <a href=\"#\" class=\"post-author\">By Julia Stiles</a>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("                            <!-- Single Post Area -->\n");
      out.write("                            <div class=\"single-post-area d-flex mb-30\">\n");
      out.write("                                <!-- Blog Thumbnail -->\n");
      out.write("                                <div class=\"blog-thumbnail\">\n");
      out.write("                                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/bg-img/13.jpg\" alt=\"\">\n");
      out.write("                                </div>\n");
      out.write("                                <!-- Blog Content -->\n");
      out.write("                                <div class=\"blog-content\">\n");
      out.write("                                    <a href=\"#\" class=\"post-title\">Burger with fries</a>\n");
      out.write("                                    <div class=\"post-meta\">\n");
      out.write("                                        <a href=\"#\" class=\"post-date\">July 11, 2018</a>\n");
      out.write("                                        <a href=\"#\" class=\"post-author\">By Julia Stiles</a>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("                            <!-- Single Post Area -->\n");
      out.write("                            <div class=\"single-post-area d-flex\">\n");
      out.write("                                <!-- Blog Thumbnail -->\n");
      out.write("                                <div class=\"blog-thumbnail\">\n");
      out.write("                                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/bg-img/14.jpg\" alt=\"\">\n");
      out.write("                                </div>\n");
      out.write("                                <!-- Blog Content -->\n");
      out.write("                                <div class=\"blog-content\">\n");
      out.write("                                    <a href=\"#\" class=\"post-title\">Avocado &amp; Oisters</a>\n");
      out.write("                                    <div class=\"post-meta\">\n");
      out.write("                                        <a href=\"#\" class=\"post-date\">July 11, 2018</a>\n");
      out.write("                                        <a href=\"#\" class=\"post-author\">By Julia Stiles</a>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("                            <!-- Single Post Area -->\n");
      out.write("                            <div class=\"single-post-area d-flex\">\n");
      out.write("                                <!-- Blog Thumbnail -->\n");
      out.write("                                <div class=\"blog-thumbnail\">\n");
      out.write("                                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/bg-img/15.jpg\" alt=\"\">\n");
      out.write("                                </div>\n");
      out.write("                                <!-- Blog Content -->\n");
      out.write("                                <div class=\"blog-content\">\n");
      out.write("                                    <a href=\"#\" class=\"post-title\">Tortilla prawns</a>\n");
      out.write("                                    <div class=\"post-meta\">\n");
      out.write("                                        <a href=\"#\" class=\"post-date\">July 11, 2018</a>\n");
      out.write("                                        <a href=\"#\" class=\"post-author\">By Julia Stiles</a>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("                            <!-- Single Post Area -->\n");
      out.write("                            <div class=\"single-post-area d-flex\">\n");
      out.write("                                <!-- Blog Thumbnail -->\n");
      out.write("                                <div class=\"blog-thumbnail\">\n");
      out.write("                                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/bg-img/16.jpg\" alt=\"\">\n");
      out.write("                                </div>\n");
      out.write("                                <!-- Blog Content -->\n");
      out.write("                                <div class=\"blog-content\">\n");
      out.write("                                    <a href=\"#\" class=\"post-title\">Burger with fries</a>\n");
      out.write("                                    <div class=\"post-meta\">\n");
      out.write("                                        <a href=\"#\" class=\"post-date\">July 11, 2018</a>\n");
      out.write("                                        <a href=\"#\" class=\"post-author\">By Julia Stiles</a>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <!-- ##### Posts Area End ##### -->\n");
      out.write("\n");
      out.write("    <!-- ##### Instagram Area Start ##### -->\n");
      out.write("    <div class=\"instagram-feed-area d-flex flex-wrap\">\n");
      out.write("        <!-- Single Instagram -->\n");
      out.write("        <div class=\"single-instagram\">\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/bg-img/home1.jpg\" style=\"width:400px;height:400px;\" alt=\"\">\n");
      out.write("            <!-- Image Zoom -->\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/bg-img/home1.jpg\" class=\"img-zoom\" title=\"Instagram Image\">+</a>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- Single Instagram -->\n");
      out.write("        <div class=\"single-instagram\">\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/bg-img/home2.jpg\"  style=\"width:400px;height:400px;\"alt=\"\">\n");
      out.write("            <!-- Image Zoom -->\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/bg-img/home2.jpg\" class=\"img-zoom\"  title=\"Instagram Image\">+</a>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- Single Instagram -->\n");
      out.write("        <div class=\"single-instagram\">\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/bg-img/home3.jpg\" style=\"width:400px;height:400px;\" alt=\"\">\n");
      out.write("            <!-- Image Zoom -->\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/bg-img/home3.jpg\" class=\"img-zoom\" title=\"Instagram Image\">+</a>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- Single Instagram -->\n");
      out.write("        <div class=\"single-instagram\">\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/bg-img/home4.jpg\" style=\"width:400px;height:400px;\" alt=\"\">\n");
      out.write("            <!-- Image Zoom -->\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/bg-img/home4.jpg\" class=\"img-zoom\"  title=\"Instagram Image\">+</a>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- Single Instagram -->\n");
      out.write("        <div class=\"single-instagram\">\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/bg-img/home5.jpg\" style=\"width:400px;height:400px;\" alt=\"\">\n");
      out.write("            <!-- Image Zoom -->\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/bg-img/home5.jpg\" class=\"img-zoom\"  title=\"Instagram Image\">+</a>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- Single Instagram -->\n");
      out.write("        <div class=\"single-instagram\">\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/bg-img/home6.jpg\" style=\"width:400px;height:400px;\" alt=\"\">\n");
      out.write("            <!-- Image Zoom -->\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/bg-img/home6.jpg\" class=\"img-zoom\"  title=\"Instagram Image\">+</a>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- Single Instagram -->\n");
      out.write("        <div class=\"single-instagram\">\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/bg-img/home7.jpg\" style=\"width:400px;height:400px;\" alt=\"\">\n");
      out.write("            <!-- Image Zoom -->\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/bg-img/home7.jpg\" class=\"img-zoom\"  title=\"Instagram Image\">+</a>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- Single Instagram -->\n");
      out.write("        <div class=\"single-instagram\">\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/bg-img/insta8.jpg\" style=\"width:400px;height:400px;\" alt=\"\">\n");
      out.write("            <!-- Image Zoom -->\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/bg-img/insta8.jpg\" class=\"img-zoom\"  title=\"Instagram Image\">+</a>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- Single Instagram -->\n");
      out.write("        <div class=\"single-instagram\">\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/bg-img/insta9.jpg\" style=\"width:400px;height:400px;\" alt=\"\">\n");
      out.write("            <!-- Image Zoom -->\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/bg-img/insta9.jpg\" class=\"img-zoom\"  title=\"Instagram Image\">+</a>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- Single Instagram -->\n");
      out.write("        <div class=\"single-instagram\">\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/bg-img/insta10.jpg\" style=\"width:400px;height:400px;\" alt=\"\">\n");
      out.write("            <!-- Image Zoom -->\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/bg-img/insta10.jpg\" class=\"img-zoom\"  title=\"Instagram Image\">+</a>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <!-- ##### Instagram Area End ##### -->\n");
      out.write("\n");
      out.write("    <!-- ##### Footer Area Start ##### -->\n");
      out.write("    <footer class=\"footer-area\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-12 col-sm-5\">\n");
      out.write("                    <!-- Copywrite Text -->\n");
      out.write("                    <p class=\"copywrite-text\"><a href=\"#\"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\n");
      out.write("Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class=\"fa fa-heart-o\" aria-hidden=\"true\"></i> by <a href=\"https://colorlib.com\" target=\"_blank\">Colorlib</a>\n");
      out.write("<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-12 col-sm-7\">\n");
      out.write("                    <!-- Footer Nav -->\n");
      out.write("                    <div class=\"footer-nav\">\n");
      out.write("                        <ul>\n");
      out.write("                            <li class=\"active\"><a href=\"#\">Home</a></li>\n");
      out.write("                            <li><a href=\"#\">Recipes</a></li>\n");
      out.write("                            <li><a href=\"#\">About Us</a></li>\n");
      out.write("                            <li><a href=\"#\">Blog</a></li>\n");
      out.write("                            <li><a href=\"#\">Contact</a></li>\n");
      out.write("                        </ul>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </footer>\n");
      out.write("    <!-- ##### Footer Area Start ##### -->\n");
      out.write("\n");
      out.write("    <!-- ##### All Javascript Script ##### -->\n");
      out.write("    <!-- jQuery-2.2.4 js -->\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery/jquery-2.2.4.min.js\"></script>\n");
      out.write("    <!-- Popper js -->\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/bootstrap/popper.min.js\"></script>\n");
      out.write("    <!-- Bootstrap js -->\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/bootstrap/bootstrap.min.js\"></script>\n");
      out.write("    <!-- All Plugins js -->\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/plugins/plugins.js\"></script>\n");
      out.write("    <!-- Active js -->\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/active.js\"></script>\n");
      out.write("</body>\n");
      out.write("<script>\n");
      out.write("    $(\".list\").hide();\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f0.setParent(null);
    // /WEB-INF/views/home.jsp(18,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setVar("path");
    // /WEB-INF/views/home.jsp(18,4) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/home.jsp(18,4) '${pageContext.request.contextPath}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
    if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /WEB-INF/views/home.jsp(64,6) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/home.jsp(64,6) '${home}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${home}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /WEB-INF/views/home.jsp(64,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("hm");
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("            <div class=\"single-slide\">\n");
          out.write("                <!-- Blog Thumbnail -->\n");
          out.write("       \n");
          out.write("                <div class=\"blog-thumbnail\">\n");
          out.write("                    <a href=\"#\"><img src=\"display?fileName=cafeimage/");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hm.cimage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" style=\"height:700px;\" alt=\"\"></a>\n");
          out.write("                </div>\n");
          out.write("\n");
          out.write("                <!-- Blog Content -->\n");
          out.write("                <div class=\"blog-content-bg\" style=\"\">\n");
          out.write("                    <div class=\"blog-content\">\n");
          out.write("                        <a href=\"#\" class=\"post-tag\">best</a>\n");
          out.write("                        <a href=\"#\" class=\"post-title\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${hm.cname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</a>\n");
          out.write("                        <div class=\"post-meta\">\n");
          out.write("\n");
          out.write("                        </div>\n");
          out.write("                    </div>\n");
          out.write("                </div>\n");
          out.write("               \n");
          out.write("            </div>\n");
          out.write("        ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f1.setParent(null);
    // /WEB-INF/views/home.jsp(145,13) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/home.jsp(145,13) '${big}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${big}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /WEB-INF/views/home.jsp(145,13) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setVar("big");
    int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
      if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("            <div class=\"row align-items-center\">\n");
          out.write("                <div class=\"col-12 col-md-6\">\n");
          out.write("                    <div class=\"big-post-thumbnail mb-50\">\n");
          out.write("                        <img src=\"display?fileName=cafeimage/");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${big.cimage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" style=\"height:540px; width:540px;\" alt=\"\">\n");
          out.write("                    </div>\n");
          out.write("                </div>\n");
          out.write("                <div class=\"col-12 col-md-6\">\n");
          out.write("                    <div class=\"big-post-content text-center mb-50\">\n");
          out.write("                        <a href=\"#\" class=\"post-tag\">The Best</a>\n");
          out.write("                        <a href=\"#\" class=\"post-title\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${big.cname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</a>\n");
          out.write("                        <div class=\"post-meta\">\n");
          out.write("                            <a href=\"#\" class=\"post-date\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${big.caddr}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</a>\n");
          out.write("                            <a href=\"#\" class=\"post-author\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${big.ctel}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</a>\n");
          out.write("                        </div>\n");
          out.write("                        <p>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${big.ccontent}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</p>\n");
          out.write("                        <a href=\"read?ccode=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${big.ccode}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" class=\"btn bueno-btn\">Read More</a>\n");
          out.write("                    </div>\n");
          out.write("                </div>\n");
          out.write("            </div>\n");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f1.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f2 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f2.setParent(null);
    // /WEB-INF/views/home.jsp(179,20) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f2.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/home.jsp(179,20) '${small}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${small}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /WEB-INF/views/home.jsp(179,20) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f2.setVar("small");
    int[] _jspx_push_body_count_c_005fforEach_005f2 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f2 = _jspx_th_c_005fforEach_005f2.doStartTag();
      if (_jspx_eval_c_005fforEach_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                    <div class=\"single-blog-post style-1 d-flex flex-wrap mb-30\">\n");
          out.write("                        <!-- Blog Thumbnail -->\n");
          out.write("                        <div class=\"blog-thumbnail\">\n");
          out.write("                            <img src=\"display?fileName=cafeimage/");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${small.cimage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" style=\"height:308px;\"alt=\"\">\n");
          out.write("                        </div>\n");
          out.write("                        <!-- Blog Content -->\n");
          out.write("                        <div class=\"blog-content\">\n");
          out.write("                            <a href=\"#\" class=\"post-tag\">The Best</a>\n");
          out.write("                            <a href=\"#\" class=\"post-title\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${small.cname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</a>\n");
          out.write("                            <div class=\"post-meta\">\n");
          out.write("                                <a href=\"#\" class=\"post-date\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${small.caddr}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</a>\n");
          out.write("                                <a href=\"#\" class=\"post-author\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${small.ctel}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</a>\n");
          out.write("                            </div>\n");
          out.write("                            <p>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${small.ccontent}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</p>\n");
          out.write("                        </div>\n");
          out.write("                    </div>\n");
          out.write("                     ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f2[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f2.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f2.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f2);
    }
    return false;
  }
}
