/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-12-27 13:30:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/spring/final1/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/final11/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1604883833700L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("   <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("   <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("   \r\n");
      out.write("<script type = \"text/javascript\" src = \"https://static.nid.naver.com/js/naverLogin_implicit-1.0.3.js\" charset=\"utf-8\"></script>\r\n");
      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\r\n");
      out.write("     \r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Favicon -->\r\n");
      out.write("     <link rel=\"icon\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/core-img/favicon2.png.jpg\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/main5.css\" />\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-3.1.1.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("h1{text-align:center}\r\n");
      out.write("#header{}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<header id=\"header\" class=\"alt\">\r\n");
      out.write("            <div class=\"inner\">\r\n");
      out.write("               <h1><a href=\"/final/\">Cafe人</a></h1>\r\n");
      out.write("               <p>Cafe人에 오신 것을 환영합니다</p>\r\n");
      out.write("               \r\n");
      out.write("            </div>\r\n");
      out.write("         </header>\r\n");
      out.write("  <h1></h1>\r\n");
      out.write("  \r\n");
      out.write("  <form name=\"frm\" >\r\n");
      out.write("    <table border=1>\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td width=100 style=\"color:#000000;font-weight:bold;\">아이디</td>\r\n");
      out.write("        <td width=300><input type=\"text\" name=\"gid\" placeholder=\"아이디를 입력하세요\"></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td style=\"color:#000000;font-weight:bold;\" >비밀번호</td>\r\n");
      out.write("        <td><input type=\"password\" name=\"gpass\" placeholder=\"비밀번호를 입력하세요\">\r\n");
      out.write("        <div id = \"lr\" style = \"color:red;\"></div>\r\n");
      out.write("        \r\n");
      out.write("        </td>  \r\n");
      out.write("          \r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("             <td colspan=2> \r\n");
      out.write("             <input type=\"submit\" value=\"login\" width=100>\r\n");
      out.write("              <button type=\"button\" onClick=\"location.href='joinInsert'\">회원가입</button>\r\n");
      out.write("              <input type=\"checkbox\" name=\"chkLogin\">로그인상태유지\r\n");
      out.write("              <div></div>\r\n");
      out.write("                          <span id = \"naver_id_login\" style=\"width:100px;margin-right:20px\"></span>  \r\n");
      out.write("                          <a id=\"custom-login-btn\" href=\"login_result2\"> \r\n");
      out.write("         <img src=\"display?fileName=kakao.png\" style=\"width:40px;\"/>\r\n");
      out.write("         </a>\r\n");
      out.write("             </td>\r\n");
      out.write("             </tr>\r\n");
      out.write("             \r\n");
      out.write("             \r\n");
      out.write("              </table> \r\n");
      out.write("             \r\n");
      out.write("         \r\n");
      out.write("  </form>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("</body>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write(" \r\n");
      out.write("         var naver_id_login = new naver_id_login(\"JYhKPQwaLJ1ye3FTdMDW\", \"http://localhost:8080/final/login_result\");    // Client ID, CallBack URL 삽입\r\n");
      out.write("                                            // 단 'localhost'가 포함된 CallBack URL\r\n");
      out.write("         var state = naver_id_login.getUniqState();\r\n");
      out.write("        \r\n");
      out.write("         naver_id_login.setButton(\"white\",1, 40);\r\n");
      out.write("         naver_id_login.setDomain(\"http://192.168.219.102:8080/final/login\");    //  URL\r\n");
      out.write("         naver_id_login.setState(state);\r\n");
      out.write("         naver_id_login.init_naver_id_login();\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write(" $(frm).submit(function(e){\r\n");
      out.write("    e.preventDefault();\r\n");
      out.write("    var gpass= $(frm.gpass).val();\r\n");
      out.write("    var gid= $(frm.gid).val();\r\n");
      out.write("           var result=\"FAIL\";\r\n");
      out.write("           var chkLogin= $(frm.chkLogin).is(\":checked\")? true: false;\r\n");
      out.write("    $.ajax({\r\n");
      out.write("      type:\"post\",\r\n");
      out.write("      url:\"login\",\r\n");
      out.write("      data:{\"gid\":gid,\"gpass\":gpass,\"chkLogin\":chkLogin},\r\n");
      out.write("      dataType:\"json\",\r\n");
      out.write("      success:function(data){\r\n");
      out.write("             \r\n");
      out.write("        if(data==0){\r\n");
      out.write("                    $(\"#lr\").html(\"아이디가 없습니다.\");  \r\n");
      out.write("                    }else if(data==2){\r\n");
      out.write("                    \t  $(\"#lr\").html(\"비밀번호가 틀립니다!\");  \r\n");
      out.write("                  }else{ \r\n");
      out.write("                \t  $(\"#lr\").html(\"로그인 되셨습니다.\");                 \r\n");
      out.write("                        var dest = '");
      out.print((String)session.getAttribute("dest"));
      out.write("';\r\n");
      out.write("                        \r\n");
      out.write("                        if(dest !=\"null\") {\r\n");
      out.write("                           location.href=\"/final/\" + dest;\r\n");
      out.write("                        }else{\r\n");
      out.write("                           location.href=\"/final\";\r\n");
      out.write("                        }  \r\n");
      out.write("                     \r\n");
      out.write("                  }\r\n");
      out.write("      }    \r\n");
      out.write("    })    \r\n");
      out.write(" });\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f0.setParent(null);
    // /WEB-INF/views/login.jsp(17,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setVar("path");
    // /WEB-INF/views/login.jsp(17,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/login.jsp(17,0) '${pageContext.request.contextPath}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
    if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
    return false;
  }
}
