/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-12-26 10:58:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_005fresult2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-3.1.1.min.js\"></script>\r\n");
      out.write(" <script src=\"https://developers.kakao.com/sdk/js/kakao.min.js\"></script>\r\n");
      out.write("   <script>\r\n");
      out.write("      Kakao.init('371a6350e4ece61cd145ad92b9a39d6e');\r\n");
      out.write("       console.log(Kakao.isInitialized());\r\n");
      out.write("   </script>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<h1>카카오 로그인 중</h1> \r\n");
      out.write("\r\n");
      out.write("<form action = \"insert\" method=\"post\" name = \"frm\" enctype=\"multipart/form-data\">\r\n");
      out.write("<input type = \"hidden\" name = \"gid\" id = \"gid\">\r\n");
      out.write("<input type = \"hidden\" name = \"gname\" id = \"gname\">\r\n");
      out.write("<input type = \"hidden\" name = \"gimage\" id = \"gimage\">\r\n");
      out.write("<input type = \"hidden\" name = \"gbirth\" id = \"gbirth\">\r\n");
      out.write("<input type = \"hidden\" name = \"gnickname\" id = \"gnickname\">\r\n");
      out.write("<input type = \"hidden\" name = \"gemail\" id = \"gemail\">\r\n");
      out.write("<input type = \"hidden\" name = \"ggender\" id = \"ggender\">\r\n");
      out.write("<input type = \"hidden\" name = \"gpass\" id = \"gpass\">\r\n");
      out.write("<input type = \"hidden\" name = \"gtel\" id = \"gtel\">\r\n");
      out.write("<input type = \"hidden\" name = \"gaddr\" id = \"gaddr\">\r\n");
      out.write("<input type=\"file\" name=\"file\">\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("loginWithKakao();\r\n");
      out.write("function loginWithKakao() {\r\n");
      out.write("    Kakao.Auth.login({\r\n");
      out.write("         success: function(authObj) {\r\n");
      out.write("            \r\n");
      out.write("            var token = authObj.access_token;\r\n");
      out.write("\r\n");
      out.write("            Kakao.API.request({\r\n");
      out.write("                url: '/v2/user/me',\r\n");
      out.write("                success: function(response) {\r\n");
      out.write("                   \r\n");
      out.write("                   \r\n");
      out.write("                   var id = response.id;\r\n");
      out.write("                   var name = response.kakao_account.profile.nickname;\r\n");
      out.write("                   var email = response.kakao_account.email;\r\n");
      out.write("                   var gender = response.kakao_account.gender;\r\n");
      out.write("                   var birthday = response.kakao_account.birthday;\r\n");
      out.write("                   var image = response.kakao_account.profile.profile_image_url;\r\n");
      out.write("                   \r\n");
      out.write("                   $(\"#gid\").val(name+id);\r\n");
      out.write("                   $(\"#gname\").val(name);\r\n");
      out.write("                   $(\"#gimage\").val(image);\r\n");
      out.write("                   $(\"#gbirth\").val(birthday);\r\n");
      out.write("                   $(\"#gemail\").val(email);\r\n");
      out.write("                   $(\"#ggender\").val(gender);\r\n");
      out.write("                   var gid = $(\"#gid\").val();\r\n");
      out.write("                   \r\n");
      out.write("                   $.ajax({\r\n");
      out.write("                   \t\r\n");
      out.write("                   \ttype:\"get\",\r\n");
      out.write("                   \turl:\"chkid\",\r\n");
      out.write("                   \tdata:{\"gid\": gid},\r\n");
      out.write("                   \tsuccess:function(data){\r\n");
      out.write("                   \t\t\r\n");
      out.write("                   \t\tif(data==1){\r\n");
      out.write("                   \t\t\t  \r\n");
      out.write("                   \t\t\t  \r\n");
      out.write("                   \t\t\t  frm.action = \"prelogin\";\r\n");
      out.write("                   \t\t\t \r\n");
      out.write("                   \t\t\t \r\n");
      out.write("                   \t\t\t  frm.submit();\r\n");
      out.write("                   \t\t}else{\r\n");
      out.write("                   \t\t\t  frm.submit();\r\n");
      out.write("                   \t\t}\r\n");
      out.write("                   \t}\r\n");
      out.write("                   \t\r\n");
      out.write("                   \t\r\n");
      out.write("                   })\r\n");
      out.write("                   \r\n");
      out.write("                  \r\n");
      out.write("                   \r\n");
      out.write("                },\r\n");
      out.write("                fail: function(error) {\r\n");
      out.write("                    console.log(error);\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("         },\r\n");
      out.write("         fail : function(err) {\r\n");
      out.write("          alert(JSON.stringify(err))\r\n");
      out.write("       },\r\n");
      out.write("      });\r\n");
      out.write("       \r\n");
      out.write("    }\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
