/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-12-26 10:27:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class read_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/spring/final1/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/final11/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/spring/final1/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/final11/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1604883833700L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.1/handlebars.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://unpkg.com/swiper/swiper-bundle.min.css\">\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-3.1.1.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"//dapi.kakao.com/v2/maps/sdk.js?appkey=4c9947b8b0448265ca15036c39a7fa4e&libraries=services,clusterer,drawing\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"//dapi.kakao.com/v2/maps/sdk.js?appkey=4c9947b8b0448265ca15036c39a7fa4e\"></script>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<!-- The above 4 meta tags *must* come first in the head; any other head content must come *after* these tags -->\r\n");
      out.write("\r\n");
      out.write("<!-- Title -->\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!-- Favicon -->\r\n");
      out.write("<link rel=\"icon\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/core-img/favicon2.png.jpg\">\r\n");
      out.write("\r\n");
      out.write("<!-- Stylesheet -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/style.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- Preloader -->\r\n");
      out.write("\t<div class=\"preloader d-flex align-items-center justify-content-center\">\r\n");
      out.write("\t\t<div class=\"preloader-content\">\r\n");
      out.write("\t\t\t<h3>Welecome Caffe人</h3>\r\n");
      out.write("\t\t\t<div id=\"cooking\">\r\n");
      out.write("\t\t\t\t<div class=\"bubble\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"bubble\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"bubble\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"bubble\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"bubble\"></div>\r\n");
      out.write("\t\t\t\t<div id=\"area\">\r\n");
      out.write("\t\t\t\t\t<div id=\"sides\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"pan\"></div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"handle\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"pancake\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"pastry\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- ##### Header Area Start ##### -->\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t<!-- ##### Header Area End ##### -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- ##### Treading Post Area Start ##### -->\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "secmenu.jsp", out, false);
      out.write("\r\n");
      out.write("\t<!-- ##### Treading Post Area End ##### -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- ##### Post Details Area Start ##### -->\r\n");
      out.write("\t<section class=\"post-news-area section-padding-100-0 mb-70\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row justify-content-center\">\r\n");
      out.write("\t\t\t\t<!-- Post Details Content Area -->\r\n");
      out.write("\t\t\t\t<div class=\"col-12 col-lg-4 col-xl-5\">\r\n");
      out.write("\t\t\t\t\t<div class=\"post-details-content mb-100\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"blog-thumbnail mb-50\">\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("#darken-background {\r\n");
      out.write("\tposition: fixed;\r\n");
      out.write("\ttop: 0px;\r\n");
      out.write("\tleft: 0px;\r\n");
      out.write("\tright: 0px;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("\tbackground: rgba(0, 0, 0, 0.5);\r\n");
      out.write("\tz-index: 10000;\r\n");
      out.write("\toverflow-y: scroll;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#lightbox {\r\n");
      out.write("\t\r\n");
      out.write("\twidth: 800px;\r\n");
      out.write("\theight: 500px;\r\n");
      out.write("\tmargin:200px auto;\r\n");
      out.write("\t\r\n");
      out.write("\tborder: 1px solid #333333;\r\n");
      out.write("\tborder-radius: 5px;\r\n");
      out.write("\tbackground: white;\r\n");
      out.write("\tbox-shadow: 0px 5px 5px rgba(34, 25, 25, 0.4);\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("#btnClose{color:white; width:100px;}\r\n");
      out.write(".swiper-container {\r\n");
      out.write("  width: 445px;\r\n");
      out.write("  height: 370px;\r\n");
      out.write("}\r\n");
      out.write(".swiper-slide {\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  font-size: 18px;\r\n");
      out.write("  background: #fff;\r\n");
      out.write("\r\n");
      out.write("  /* Center slide text vertically */\r\n");
      out.write("  display: -webkit-box;\r\n");
      out.write("  display: -ms-flexbox;\r\n");
      out.write("  display: -webkit-flex;\r\n");
      out.write("  display: flex;\r\n");
      out.write("  -webkit-box-pack: center;\r\n");
      out.write("  -ms-flex-pack: center;\r\n");
      out.write("  -webkit-justify-content: center;\r\n");
      out.write("  justify-content: center;\r\n");
      out.write("  -webkit-box-align: center;\r\n");
      out.write("  -ms-flex-align: center;\r\n");
      out.write("  -webkit-align-items: center;\r\n");
      out.write("  align-items: center;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\t\t\t\t\t\t<!-- Swiper -->\r\n");
      out.write("\t<div class=\"swiper-container\">\r\n");
      out.write("\t\t<div class=\"swiper-wrapper\">\r\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- Add Arrows -->\r\n");
      out.write("\t\t<div class=\"swiper-button-next\"></div>\r\n");
      out.write("\t\t<div class=\"swiper-button-prev\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Swiper JS -->\r\n");
      out.write("\t<script src=\"https://unpkg.com/swiper/swiper-bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Initialize Swiper -->\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"blog-content\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"post-tag\">Category</a>\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"post-title\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.cname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"post-meta mb-50\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"post-date\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.caddr}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</a> <a href=\"#\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"post-author\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.ctel}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<h4>\r\n");
      out.write("\t\t\t\t\t\t\t\tBest Review <button style=\"float: right; font-size: 13px;background-color: transparent !important;border:none;\" onClick=\"location.href='reply?ccode=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.ccode}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\">더보기<img\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/core-img/add.png\"></button>\r\n");
      out.write("\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"bestReview\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t<script id=\"tempBR\" type=\"text/x-handlebars-template\">\r\n");
      out.write("\t\t\t\t\t\t\t{{#each br}}\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"best\" style=\"width: 445px; height: 190px; overflow: hidden;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"width: 110px; height: 170px; padding: 10px; margin: 5px; color: white; float: left; font-size: 15px; text-align: center;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img style=\"width:90px;height:90px; border-radius:45px;\" src=\"{{gmember gimage}}\"  alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div style=\"width: 90px; height: 20px; margin-bottom: 3px; font-size: 16px; line-height: 1.3; text-align: center; word-break: break-all; color: #555555;\">{{gnickname}}</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div style=\"width: 90px; height: 20px; margin-bottom: 3px;margin-top:2px; font-size: 14px; line-height: 1.3; text-align: center; word-break: break-all; color: #555555;\"><button rcode=\"{{rcode}}\" class=\"btnGood\" style=\"border:none;background-color: transparent !important;\"><img style=\"width:15px;height:15px;\" src=\"{{check good}}\">&nbsp;좋아요</button>{{count}}개</div>\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"review\" style=\"cursor:pointer;width: 300px; height: 180px; padding: 10px; margin: 5px; color: white; float: left; font-size: 15px; text-align: center;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span style=\"width: 70px; height: 20px; margin-bottom: 2px; color: #000000; line-height: 1.3; word-break: break-all;\">{{dateFormat rdate}}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;평점: {{rscope}}점</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>{{rcontent}}</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"reviewImage\" rcode=\"{{rcode}}\" content=\"{{rcontent}}\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t{{#isVowel}}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div gid={{gid}} style=\"text-align:right;\"><button style=\"background-color: transparent !important;border:none;\" onClick=\"location.href='reviewUpdate?rcode={{rcode}}&ccode={{ccode}}'\">수정</button> / <button id=\"reviewDelete\" rcode=\"{{rcode}}\" style=\"background-color: transparent !important;border:none;\">삭제</button></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t{{else}}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t{{/isVowel}}\r\n");
      out.write("\t\t\t\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t\t\t\t{{/each}}\t\r\n");
      out.write("\t\t\t\t\t\t\t</script>\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"darken-background\">\r\n");
      out.write("\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/core-img/x.png\" id=\"btnClose\" alt=\"\" style=\"float:right; width:30px;height:30px;margin:10px\">\r\n");
      out.write("\t\t\t\t\t<div id=\"lightbox\">\r\n");
      out.write("\t\t\t\t\t\t<img id=\"image\" src=\"http://placehold.it/222x296\" style=\"width:500px; height:500px; \" >\r\n");
      out.write("\t\t\t\t\t\t<div id=\"here\" style=\"height:50%; max-hight:50%; overflow-y: auto;\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"contents\" style=\"margin-left:20px;margin-bottom:20px; margin-right:20px;\"></div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<script>\r\n");
      out.write("\t\t\t\tHandlebars.registerHelper('isVowel', function(options) {\r\n");
      out.write("\t\t\t\t\t  var regexp = '");
      out.print(session.getAttribute("gid"));
      out.write("';\r\n");
      out.write("\t\t\t\t\t  if (regexp==(this.gid)) {\r\n");
      out.write("\t\t\t\t\t    return options.fn(this);\r\n");
      out.write("\t\t\t\t\t  } else {\r\n");
      out.write("\t\t\t\t\t    return options.inverse(this);\r\n");
      out.write("\t\t\t\t\t  }\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\tHandlebars.registerHelper(\"check\", function(good) {\r\n");
      out.write("\t\t\t\t\tif(good==0){\r\n");
      out.write("\t\t\t\t   \t\treturn \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/core-img/heart_no.png\";\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\treturn \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/core-img/heart_color.png\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t   });\r\n");
      out.write("\t\t\t\tHandlebars.registerHelper(\"dateFormat\", function(rdate) {\r\n");
      out.write("\t\t\t\t       return new Handlebars.SafeString(\r\n");
      out.write("\t\t\t\t           moment(rdate).format(\"YYYY년MM월DD일\").toUpperCase()\r\n");
      out.write("\t\t\t\t       );\r\n");
      out.write("\t\t\t\t   });\r\n");
      out.write("\t\t\t\tHandlebars.registerHelper(\"gmember\", function(gimage) {\r\n");
      out.write("\t\t\t\t\tif(gimage==null){\r\n");
      out.write("\t\t\t\t   \t\treturn \"http://placehold.it/90x90\";\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\treturn \"display?fileName=\"+gimage;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\tgoodCount();\r\n");
      out.write("\t\t\t\tfunction goodCount(){\r\n");
      out.write("\t\t\t\t\tvar ccode=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.ccode}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\ttype:\"get\",\r\n");
      out.write("\t\t\t\t\t\turl:\"bestReview\",\r\n");
      out.write("\t\t\t\t\t\tdata:{\"ccode\":ccode},\r\n");
      out.write("\t\t\t\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\t\t\t\tvar temp=Handlebars.compile($(\"#tempBR\").html());\r\n");
      out.write("\t\t\t\t\t         $(\".bestReview\").html(temp(data));\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t         $(\".btnGood\").on(\"click\",function(){\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar ccode=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.ccode}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar rcode=$(this).attr(\"rcode\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar img=$(this).children(\"img\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar isLogin ='");
      out.print(session.getAttribute("gid"));
      out.write("' == 'null' ? false: true;\r\n");
      out.write("\t\t\t\t\t\t\t\t\tif(isLogin){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttype:\"post\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\turl:\"good\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata:{\"rcode\":rcode},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tif(data==1){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tgoodCount();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tgoodCount();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tlocation.href=\"good?ccode=\"+ccode;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t         $(\".reviewImage\").each(function(){\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar reviewImage = $(this);\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar rcode=$(this).attr(\"rcode\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttype:\"get\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\turl:\"reviewImage\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdata:{\"rcode\":rcode},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar str=\"\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t$.each(data,function(index,items){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tstr += \"<img class='hide' style='margin:10px;' src='display?fileName=attach/\"+items+\"' width=100>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\treviewImage.html(str);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t$(\".hide\").hide();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t         \r\n");
      out.write("\t\t\t\t\t\t\t\t$(\".best\").on(\"click\",\".review\",function(){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  var img=$(this).parent().next();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  var src=img.children().attr(\"src\");  \r\n");
      out.write("\t\t\t\t\t\t\t\t      var content=img.attr(\"content\");\r\n");
      out.write("\t\t\t\t\t\t\t\t      $(\"#image\").attr(\"src\",src);\r\n");
      out.write("\t\t\t\t\t\t\t\t      $(\"#contents\").html(content);\r\n");
      out.write("\t\t\t\t\t\t\t\t      $(\"#darken-background\").show();\r\n");
      out.write("\t\t\t\t\t\t\t\t   });\r\n");
      out.write("\t\t\t\t\t\t\t\t   $(\"#btnClose\").on(\"click\",function(){\r\n");
      out.write("\t\t\t\t\t\t\t\t      $(\"#darken-background\").hide();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t   });\r\n");
      out.write("\t\t\t\t\t\t\t\t   $(\"#reviewDelete\").on(\"click\",function(){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvar rcode=$(this).attr(\"rcode\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tif(!confirm(\"정말로 삭제하실건가요?\")) return;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttype:\"post\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\turl:\"reivewDelete\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata:{\"rcode\":rcode},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tsuccess:function(){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\talert(\"삭제되었습니다.\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t         \r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t<div class=\"col-12 col-lg-4 col-xl-4\">\r\n");
      out.write("\t\t\t\t\t<!-- Info -->\r\n");
      out.write("\t\t\t\t\t<div class=\"recipe-info\">\r\n");
      out.write("\t\t\t\t\t\t<h5>Info</h5>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"info-data\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/core-img/eye.png\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span id=\"viewCnt\">1,577 Views(조회수)</span></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/core-img/review.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\talt=\"\"> <span id=\"totalReview\">리뷰 수</span></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/core-img/favorites.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\talt=\"\"> <span id=\"totalFavorites\">즐겨찾기 수</span></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/core-img/scope.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\talt=\"\"> <span id=\"avgScope\">평점</span></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- Ingredients -->\r\n");
      out.write("\t\t\t\t\t<div class=\"ingredients\">\r\n");
      out.write("\t\t\t\t\t\t<h5>카페 메뉴</h5>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- Custom Checkbox -->\r\n");
      out.write("\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Sidebar Widget -->\r\n");
      out.write("\t\t\t\t<div class=\"col-12 col-sm-9 col-md-6 col-lg-4 col-xl-3\">\r\n");
      out.write("\t\t\t\t\t<div class=\"sidebar-area\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- Single Widget Area -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"single-widget-area author-widget mb-30\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"background-pattern bg-img\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"background:#E1DEC3; \">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"author-thumbnail\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\" margin-top:50px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button id=\"btnReview\" style=\"background-color: transparent !important;border:none; margin-bottom:10px;margin-rigth:10px;\" onClick=\"location.href='reviewInsert?ccode=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.ccode}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/core-img/review.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\talt=\"\"><span style=\"font-size: 0.8rem;\">리뷰쓰기</span></button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button id=\"btnFavorite\" style=\"background-color: transparent !important;border:none;\"><span id=\"favorites\" style=\"font-size:29px; \"><img style=\"width:30px;height:30px;\" src=\"\"></span><span style=\"font-size: 0.8rem;\">즐겨찾기</span></button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"social-info\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"https://section.blog.naver.com/Search/Post.nhn?pageNo=1&rangeType=ALL&orderBy=sim&keyword=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.cname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/core-img/naver.jpg\" alt=\"\"></i></a> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"http://search.daum.net/search?w=blog&f=section&m=&SA=daumsec&lpp=10&nil_profile=vsearch&nil_src=blog&q=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.cname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"><img\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/core-img/daum.jpg\" alt=\"\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- Single Widget Area -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"single-widget-area add-widget mb-30\">\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"map\" style=\"width: 255px; height: 353px;\"></div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!-- Single Widget Area 주변 카페 -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"single-widget-area post-widget mb-30\"></div>\r\n");
      out.write("\t\t\t\t\t\t<script id=\"temp\" type=\"text/x-handlebars-template\">\r\n");
      out.write("\t\t\t\t\t\t\t{{#each list}}\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"single-post-area d-flex\" style=\"cursor:pointer;\" ccode={{ccode}} x={{x}} y={{y}}>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"blog-thumbnail\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"{{isImage cimage}}\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"blog-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"post-title\"><b>{{cname}}</b></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"post-meta\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"post-date\">{{cutting caddr}}</span> \t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"post-meta\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"post-author\">{{rscope}}점</span>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t{{/each}}\r\n");
      out.write("\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\t\tHandlebars.registerHelper(\"cutting\", function(caddr) {\r\n");
      out.write("\t\t\t\t\t\t\treturn caddr.split(\" \",2)[0]+\" \"+caddr.split(\" \",2)[1];\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\tHandlebars.registerHelper(\"isImage\", function(cimage) {\r\n");
      out.write("\t\t\t\t\t\t\tif(cimage==\"\"||cimage==null){\r\n");
      out.write("\t\t\t\t\t\t   \t\treturn \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/bg-img/12.jpg\";\r\n");
      out.write("\t\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t\treturn \"display?fileName=cafeimage/\"+cimage;\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t\t<!-- Single Widget Area -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"single-widget-area newsletter-widget mb-30\">\r\n");
      out.write("\t\t\t\t\t\t\t<h5>카페 느낌(태그)</h5>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- Custom Checkbox -->\r\n");
      out.write("\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- ##### Instagram Area End ##### -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- ##### Footer Area Start ##### -->\r\n");
      out.write("\t<footer class=\"footer-area\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-12 col-sm-5\">\r\n");
      out.write("\t\t\t\t\t<!-- Copywrite Text -->\r\n");
      out.write("\t\t\t\t\t<p class=\"copywrite-text\">\r\n");
      out.write("\t\t\t\t\t\t<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("\t\t\t\t\t\tCopyright &copy;\r\n");
      out.write("\t\t\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\t\t\tdocument.write(new Date().getFullYear());\r\n");
      out.write("\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t\tAll rights reserved | This template is made with <i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"fa fa-heart-o\" aria-hidden=\"true\"></i> by <a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"https://colorlib.com\" target=\"_blank\">Colorlib</a>\r\n");
      out.write("\t\t\t\t\t\t<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-12 col-sm-7\">\r\n");
      out.write("\t\t\t\t\t<!-- Footer Nav -->\r\n");
      out.write("\t\t\t\t\t<div class=\"footer-nav\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"active\"><a href=\"#\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">Recipes</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">About Us</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">Blog</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">Contact</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("\t<!-- ##### Footer Area Start ##### -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- ##### All Javascript Script ##### -->\r\n");
      out.write("\t<!-- jQuery-2.2.4 js -->\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery/jquery-2.2.4.min.js\"></script>\r\n");
      out.write("\t<!-- Popper js -->\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/bootstrap/popper.min.js\"></script>\r\n");
      out.write("\t<!-- Bootstrap js -->\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/bootstrap/bootstrap.min.js\"></script>\r\n");
      out.write("\t<!-- All Plugins js -->\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/plugins/plugins.js\"></script>\r\n");
      out.write("\t<!-- Active js -->\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/active.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("var ccode=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.ccode}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("getTotalFavorites();\r\n");
      out.write("getNearbyCafe();\r\n");
      out.write("function getTotalFavorites(){\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\ttype:\"get\",\r\n");
      out.write("\t\turl:\"info.json\",\r\n");
      out.write("\t\tdata:{\"ccode\":ccode},\r\n");
      out.write("\t\tsuccess:function(data){\r\n");
      out.write("\t\t\tvar scope=Number(data.scope);\r\n");
      out.write("\t\t\t$(\"#totalFavorites\").html(data.favorites+\" 명\");\r\n");
      out.write("\t\t\t$(\"#totalReview\").html(data.review+\" 개\");\r\n");
      out.write("\t\t\t$(\"#viewCnt\").html(data.vo.viewcnt+\" 회\");\r\n");
      out.write("\t\t\t$(\"#avgScope\").html(scope.toFixed(1)+\" 점\");\r\n");
      out.write("\t\t\tif(data.favorite==1){\r\n");
      out.write("\t\t\t\t$(\"#favorites\").children(\"img\").attr(\"src\",\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/core-img/free_staron.png\");\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\t$(\"#favorites\").children(\"img\").attr(\"src\",\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/core-img/free_star.png\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("function getNearbyCafe(){\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\ttype:\"get\",\r\n");
      out.write("\t\turl:\"nearbysearch.json\",\r\n");
      out.write("\t\tdata:{\"ccode\":ccode},\r\n");
      out.write("\t\tsuccess:function(data){\r\n");
      out.write("\t\t\tvar temp=Handlebars.compile($(\"#temp\").html());\r\n");
      out.write("\t         $(\".single-widget-area.post-widget.mb-30\").html(temp(data));\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("$(\".single-widget-area.post-widget.mb-30\").on(\"click\",\".single-post-area.d-flex\",function(){\r\n");
      out.write("\tvar ccode=$(this).attr(\"ccode\");\r\n");
      out.write("\tlocation.href = \"read?ccode=\" + ccode;\r\n");
      out.write("});\r\n");
      out.write("\t\t\t\t$(\".single-instagram\").on(\"click\",function(e){\r\n");
      out.write("\t\t\t\t\te.preventDefault();\r\n");
      out.write("\t\t\t\t\t  var img=$(this).children(\"img\");\r\n");
      out.write("\t\t\t\t      var src=img.attr(\"src\");\r\n");
      out.write("\t\t\t\t      var contents=img.attr(\"contents\");\r\n");
      out.write("\t\t\t\t      $(\"#image\").attr(\"src\",src);\r\n");
      out.write("\t\t\t\t      $(\"#contents\").html(contents);\r\n");
      out.write("\t\t\t\t      $(\"#darken-background\").show();\r\n");
      out.write("\t\t\t\t   });\r\n");
      out.write("\t\t\t\t   $(\"#btnClose\").on(\"click\",function(){\r\n");
      out.write("\t\t\t\t      $(\"#darken-background\").hide();\r\n");
      out.write("\t\t\t\t   });\r\n");
      out.write("\t\t\t\t   var swiper = new Swiper('.swiper-container', {\r\n");
      out.write("\t\t\t\t\t      navigation: {\r\n");
      out.write("\t\t\t\t\t        nextEl: '.swiper-button-next',\r\n");
      out.write("\t\t\t\t\t        prevEl: '.swiper-button-prev',\r\n");
      out.write("\t\t\t\t\t      },\r\n");
      out.write("\t\t\t\t\t    });\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t$(\"#btnFavorite\").on(\"click\",function(){\r\n");
      out.write("\t\t\t\t\t\tvar ccode=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.ccode}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("\t\t\t\t\t\tvar isLogin ='");
      out.print(session.getAttribute("gid"));
      out.write("' == 'null' ? false\r\n");
      out.write("\t\t\t\t\t\t\t\t: true;\r\n");
      out.write("\t\t\t\t\t\t//값이 true면 로그인이 된 상태 false면 로그인이 되지 않은 상태 \r\n");
      out.write("\t\t\t\t\t\tif (isLogin) { // favorite post로 인하여 ajax처리되어 즐겨찾기 \r\n");
      out.write("\t\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\t\t\t\t\turl : \"favorite\",\r\n");
      out.write("\t\t\t\t\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"ccode\" : ccode\r\n");
      out.write("\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tif (data == 1) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\talert(\"즐겨찾기를 등록 하셨습니다.\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tgetTotalFavorites();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\talert(\"즐겨찾기를 해제 하셨습니다.\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tgetTotalFavorites();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\tlocation.href = \"favorite?ccode=\" + ccode; //favorite get으로 이동하여 interceptor 적용 login page 이동\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\tvar container = document.getElementById('map');\r\n");
      out.write("\tvar options = {\r\n");
      out.write("\t\tcenter : new kakao.maps.LatLng(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.y}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\", \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.x}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"),\r\n");
      out.write("\t\tlevel : 3\r\n");
      out.write("\t};\r\n");
      out.write("\r\n");
      out.write("\tvar map = new kakao.maps.Map(container, options);\r\n");
      out.write("\r\n");
      out.write("\t// 마커가 표시될 위치입니다 \r\n");
      out.write("\tvar markerPosition = new kakao.maps.LatLng(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.y}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\", \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.x}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\");\r\n");
      out.write("\r\n");
      out.write("\t// 마커를 생성합니다\r\n");
      out.write("\tvar marker = new kakao.maps.Marker({\r\n");
      out.write("\t\tposition : markerPosition\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t// 마커가 지도 위에 표시되도록 설정합니다\r\n");
      out.write("\tmarker.setMap(map);\r\n");
      out.write("\t// 마커에 커서가 오버됐을 때 마커 위에 표시할 인포윈도우를 생성합니다\r\n");
      out.write("\tvar iwContent = '<div style=\"padding:3px;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.cname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>'; // 인포윈도우에 표출될 내용으로 HTML 문자열이나 document element가 가능합니다\r\n");
      out.write("\r\n");
      out.write("\t// 인포윈도우를 생성합니다\r\n");
      out.write("\tvar infowindow = new kakao.maps.InfoWindow({\r\n");
      out.write("\t    content : iwContent\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t// 마커에 마우스오버 이벤트를 등록합니다\r\n");
      out.write("\tkakao.maps.event.addListener(marker, 'mouseover', function() {\r\n");
      out.write("\t  // 마커에 마우스오버 이벤트가 발생하면 인포윈도우를 마커위에 표시합니다\r\n");
      out.write("\t    infowindow.open(map, marker);\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t// 마커에 마우스아웃 이벤트를 등록합니다\r\n");
      out.write("\tkakao.maps.event.addListener(marker, 'mouseout', function() {\r\n");
      out.write("\t    // 마커에 마우스아웃 이벤트가 발생하면 인포윈도우를 제거합니다\r\n");
      out.write("\t    infowindow.close();\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f0.setParent(null);
    // /WEB-INF/views/read.jsp(25,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setVar("path");
    // /WEB-INF/views/read.jsp(25,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/read.jsp(25,0) '${pageContext.request.contextPath}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
    if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /WEB-INF/views/read.jsp(129,3) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/read.jsp(129,3) '${cafeImage}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${cafeImage}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /WEB-INF/views/read.jsp(129,3) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("image");
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t<div class=\"swiper-slide\"><img style=\"height:370px;\" src=\"display?fileName=cafeimage/");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${image.image}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"></div>\r\n");
          out.write("\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f1.setParent(null);
    // /WEB-INF/views/read.jsp(324,6) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/read.jsp(324,6) '${menu}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${menu}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /WEB-INF/views/read.jsp(324,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setVar("menu");
    int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
      if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t<div class=\"custom-control custom-checkbox\" style=\"overflow:hidden;\">\r\n");
          out.write("\t\t\t\t\t\t\t\t<div style=\"width:100px;height:85px;float:left;margin-right:30px;\"><img style=\"width:90px;height:90px;\" src=\"display?fileName=menuimages/");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${menu.image}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"></div>\r\n");
          out.write("\t\t\t\t\t\t\t\t<div style=\"width:110px;height:85px;float:left;\"><div><b style=\"font-size:20px;\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${menu.menu}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</b></div><span>");
          if (_jspx_meth_fmt_005fformatNumber_005f0(_jspx_th_c_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
            return true;
          out.write("원</span></div>\r\n");
          out.write("\t\t\t\t\t\t\t</div>\t\r\n");
          out.write("\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f1.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    _jspx_th_fmt_005fformatNumber_005f0.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fformatNumber_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f1);
    // /WEB-INF/views/read.jsp(327,117) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatNumber_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${menu.price}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    // /WEB-INF/views/read.jsp(327,117) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatNumber_005f0.setPattern("#,###");
    int _jspx_eval_fmt_005fformatNumber_005f0 = _jspx_th_fmt_005fformatNumber_005f0.doStartTag();
    if (_jspx_th_fmt_005fformatNumber_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /WEB-INF/views/read.jsp(342,9) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.cimage==null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t\t\t<img src=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("/resources/img/bg-img/23.jpg\" alt=\"\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent(null);
    // /WEB-INF/views/read.jsp(345,9) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.cimage!=null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t\t\t<img src=\"display?fileName=/cafeimage/");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.cimage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\" alt=\"\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f2 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f2.setParent(null);
    // /WEB-INF/views/read.jsp(406,6) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f2.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/read.jsp(406,6) '${tag}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${tag}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /WEB-INF/views/read.jsp(406,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f2.setVar("t");
    int[] _jspx_push_body_count_c_005fforEach_005f2 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f2 = _jspx_th_c_005fforEach_005f2.doStartTag();
      if (_jspx_eval_c_005fforEach_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t<div class=\"custom-control custom-checkbox\">\r\n");
          out.write("\t\t\t\t\t\t\t<label class=\"custom-control-label\" for=\"customCheck1\"><a\r\n");
          out.write("\t\t\t\t\t\t\t\thref=\"\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${t.tag}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</a></label>\r\n");
          out.write("\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f2[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f2.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f2.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f2);
    }
    return false;
  }
}
