/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-12-27 15:28:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class reply_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/spring/final1/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/final11/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1604883833700L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-3.1.1.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.1/handlebars.js\"></script>\r\n");
      out.write("<!-- The above 4 meta tags *must* come first in the head; any other head content must come *after* these tags -->\r\n");
      out.write("<title>Cafe人 - 카페를 좋아하는 사람들</title>\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!-- Favicon -->\r\n");
      out.write("<link rel=\"icon\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/core-img/favicon2.png.jpg\">\r\n");
      out.write("\r\n");
      out.write("<!-- Stylesheet -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/style.css\">\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".box img {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tbox-shadow: 5px 5px 5px gray;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".title {\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".price {\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#darken-background {\r\n");
      out.write("\tposition: fixed;\r\n");
      out.write("\ttop: 0px;\r\n");
      out.write("\tleft: 0px;\r\n");
      out.write("\tright: 0px;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("\tbackground: rgba(0, 0, 0, 0.5);\r\n");
      out.write("\tz-index: 10000;\r\n");
      out.write("\toverflow-y: scroll;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#lightbox {\r\n");
      out.write("\t\r\n");
      out.write("\twidth: 800px;\r\n");
      out.write("\theight: 500px;\r\n");
      out.write("\tmargin:200px auto;\r\n");
      out.write("\t\r\n");
      out.write("\tborder: 1px solid #333333;\r\n");
      out.write("\tborder-radius: 5px;\r\n");
      out.write("\tbackground: white;\r\n");
      out.write("\tbox-shadow: 0px 5px 5px rgba(34, 25, 25, 0.4);\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("#btnClose{color:white; width:100px;}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- 시작시 뜨는 후라이팬 -->\r\n");
      out.write("\t<div class=\"preloader d-flex align-items-center justify-content-center\">\r\n");
      out.write("\t\t<div class=\"preloader-content\">\r\n");
      out.write("\t\t\t<h3>Welecome Caffe人</h3>\r\n");
      out.write("\t\t\t<div id=\"cooking\">\r\n");
      out.write("\t\t\t\t<div class=\"bubble\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"bubble\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"bubble\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"bubble\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"bubble\"></div>\r\n");
      out.write("\t\t\t\t<div id=\"area\">\r\n");
      out.write("\t\t\t\t\t<div id=\"sides\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"pan\"></div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"handle\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"pancake\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"pastry\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- ##### Treading Post Area End ##### -->\r\n");
      out.write("\t\r\n");
      out.write("\t   <!-- ##### Instagram Area Start ##### -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\t   \r\n");
      out.write("\t<div class=\"container\" style=\"margin:auto;\">\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"instagram-feed-area d-flex flex-wrap\" style=\"margin-top:100px;\">\r\n");
      out.write("     \r\n");
      out.write("      <div >\r\n");
      out.write("       <div id=\"cimage\" style=\"margin:auto;\"><img src=\"display?fileName=cafeimage/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rlist.cimage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" \" style=\"width:200px; height:200px; border-radius:100px;\" >\r\n");
      out.write("      <span id=\"name\" style=\"font-size:30px;  margin-bottom:100px; margin-left:2%\"><b>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rlist.cname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</b></span> \r\n");
      out.write("    </div>\r\n");
      out.write("   <div id=\"gigi\" style=\"margin-top:50px;\">\r\n");
      out.write("   \r\n");
      out.write("       ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write(" \r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("   </div>\r\n");
      out.write("   \r\n");
      out.write("\t<!-- ##### Instagram Area End ##### -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- ##### Footer Area Start ##### -->\r\n");
      out.write("\t<footer class=\"footer-area\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-12 col-sm-5\">\r\n");
      out.write("\t\t\t\t\t<!-- Copywrite Text -->\r\n");
      out.write("\t\t\t\t\t<p class=\"copywrite-text\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("\t\t\t\t\t\t\tCopyright &copy;<script>\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.write(new Date().getFullYear());\r\n");
      out.write("\t\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t\t\tAll rights reserved | This template is made with \r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"fa fa-heart-o\" aria-hidden=\"true\"></i> by \r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"https://colorlib.com\" target=\"_blank\">Colorlib</a> <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-12 col-sm-7\">\r\n");
      out.write("\t\t\t\t\t<!-- Footer Nav -->\r\n");
      out.write("\t\t\t\t\t<div class=\"footer-nav\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"active\"><a href=\"#\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">Recipes</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">About Us</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">Blog</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">Contact</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("\t<!-- ##### Footer Area Start ##### -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- ##### All Javascript Script ##### -->\r\n");
      out.write("\t<!-- jQuery-2.2.4 js -->\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery/jquery-2.2.4.min.js\"></script>\r\n");
      out.write("\t<!-- Popper js -->\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/bootstrap/popper.min.js\"></script>\r\n");
      out.write("\t<!-- Bootstrap js -->\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/bootstrap/bootstrap.min.js\"></script>\r\n");
      out.write("\t<!-- All Plugins js -->\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/plugins/plugins.js\"></script>\r\n");
      out.write("\t<!-- Active js -->\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/active.js\"></script>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<script>\r\n");
      out.write("\t\t\tHandlebars.registerHelper(\"printImg\", function(img){\r\n");
      out.write("\t\t\t\tif(!img) return \"http://placehold.it/150x220\"\r\n");
      out.write("\t\t\t\telse return img;\r\n");
      out.write("     \t\t});\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\r\n");
      out.write("\t\t<div id = \"darken-background\">\r\n");
      out.write("\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/core-img/x.png\" id=\"btnClose\" alt=\"\" style=\"float:right; width:30px;height:30px;margin:10px\">\r\n");
      out.write("\t\t\r\n");
      out.write("      <div id = \"lightbox\" style=\"overflow:hidden\">\r\n");
      out.write("\t\t<div style=\"float:left; left:0px; bottom:0px;  \">\r\n");
      out.write("\t\t\t<img id=\"image\" src=\"http://placehold.it/222x296\" style=\"width:500px; height:500px; \" >\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t<img src=\"http://placehold.it/50x50\" id=\"proimage\" alt=\"\" style=\"width:50px;height:50px; border-radius:50px;margin-top:20px;margin-left:20px;margin-bottom:50px;\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<span id=\"nick\" style=\"\" ></span>\r\n");
      out.write("\t\t\t<div id=\"here\" style=\"height:45%; max-hight:40%; overflow-y: auto;\">\r\n");
      out.write("\t\t\t<div id=\"contents\" style=\"margin-left:20px;margin-bottom:20px; margin-right:20px;\" ></div>\r\n");
      out.write("\t\t\t<div id=\"comment\" style=\"\"></div>\r\n");
      out.write("\t\t\t<div class=\"rcode\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<script id=\"temp\" type=\"text/x-handlebars-template\">\r\n");
      out.write("            {{#each .}}\r\n");
      out.write("                <div style=\"margin-left:20px\"> <span><b>{{gid}}</b></span>:<span>{{rccontent}}</span> <span><p>{{rcdate}}</p></span></div>                          \r\n");
      out.write("\t            <input type=\"hidden\" id=\"rcode\" value={{rcode}}>\r\n");
      out.write("\r\n");
      out.write("                {{/each}}\r\n");
      out.write("\r\n");
      out.write("\t\t\t</script>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t <span style=\"margin-left:20px;\"><button class=\"btnGood\" style=\"border:none;background-color: transparent !important;\"></button> <br>  <button class = \"reviewUpdate\" style=\"background-color: transparent !important;border:none;\">  수정</button> / <button class=\"reviewDelete\" style=\"background-color: transparent !important;border:none;\">삭제</button></span>\r\n");
      out.write("\t\t\t<textarea class=\"rccontent\"  cols=\"30\" rows=\"4\" placeholder=\"Message\" style=\" margin-top:2%; margin-left:18px; \"></textarea>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<input type=\"button\" id=\"btnInsert\" style=\"border:0px; background:white;margin-left:1%; margin-bottom:2% \"   value=\"게시\" >\r\n");
      out.write("\t\t\t<input type=\"hidden\" class=\"gid\" name=\"gid\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${gid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\t  \r\n");
      out.write("\t\t\t\t</div>\t\r\n");
      out.write("\t\t        \r\n");
      out.write("\t\t</div>\t\r\n");
      out.write("\t\t\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("$(\".pimage\").hide();\r\n");
      out.write("$(\".rcode\").hide();\r\n");
      out.write("$(\"#btnInsert\").on(\"click\",function(){\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\tvar gid1=$(this).parent().find(\".gid\");\r\n");
      out.write("\tvar gid2=gid1.val();\r\n");
      out.write("\tvar rccontent=$(this).parent().find(\".rccontent\");\r\n");
      out.write("\tvar rccontent1=rccontent.val();\r\n");
      out.write("\tvar rcode=$(this).parent().find(\"#here\");\r\n");
      out.write("\tvar rcode1=rcode.find(\".rcode\").html();\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t$.ajax({\r\n");
      out.write(" \t\ttype:\"post\",\r\n");
      out.write(" \t\turl:\"reinsert\",\r\n");
      out.write(" \t\tdata:{\"gid\":gid2,\"rccontent\":rccontent1,\"rcode\":rcode1},\r\n");
      out.write(" \t\tsuccess:function(){\r\n");
      out.write(" \t\t\t\r\n");
      out.write(" \t\t\t $.ajax({\r\n");
      out.write("          \t\ttype:\"get\",\r\n");
      out.write("          \t\turl:\"replycomment\",\r\n");
      out.write("          \t\tdata:{\"rcode\":rcode1},\r\n");
      out.write("          \t\tsuccess:function(data){\r\n");
      out.write("          \t\t\t\r\n");
      out.write("          \t\t\t \r\n");
      out.write("          \t\tvar temp=Handlebars.compile($(\"#temp\").html());\r\n");
      out.write("          \t\t\r\n");
      out.write("          \t     $(\"#comment\").html(temp(data));\r\n");
      out.write("     \r\n");
      out.write("\t\t   }     \r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("               });\r\n");
      out.write(" \t\t\t\r\n");
      out.write("       }     \r\n");
      out.write("\t\t\r\n");
      out.write("      });\r\n");
      out.write("  \r\n");
      out.write("})\r\n");
      out.write("            $(\".single-instagram\").on(\"click\",function(e){\r\n");
      out.write("               e.preventDefault();\r\n");
      out.write("             \r\n");
      out.write("               var img=$(this).children(\"img\");\r\n");
      out.write("               var src=img.attr(\"src\");\r\n");
      out.write("               var contents=$(this).find(\".content\").val();\r\n");
      out.write("               var nick=$(this).find(\".nick\").val();\r\n");
      out.write("               var hi=$(this).children(\".pimage\");\r\n");
      out.write("               var pimage=hi.children(\"img\");\r\n");
      out.write("               var pimage2=pimage.attr(\"src\");\r\n");
      out.write("               var rcode=$(this).find(\".rcode\").val();\r\n");
      out.write("               $(\"#darken-background\").show();\t\r\n");
      out.write("               $(\"#image\").attr(\"src\",src);\r\n");
      out.write("                  $.ajax({\r\n");
      out.write("             \t\ttype:\"get\",\r\n");
      out.write("             \t\turl:\"replycomment\",\r\n");
      out.write("             \t\tdata:{\"rcode\":rcode},\r\n");
      out.write("             \t\tsuccess:function(data){\r\n");
      out.write("             \t\t\t\r\n");
      out.write("             \t\tvar temp=Handlebars.compile($(\"#temp\").html());\r\n");
      out.write("             \t\t\r\n");
      out.write("             \t     $(\"#comment\").html(temp(data));\r\n");
      out.write("             \t     \r\n");
      out.write("             \t     \r\n");
      out.write("                         $(\"#contents\").html(contents);\r\n");
      out.write("                         $(\"#nick\").html(nick);\r\n");
      out.write("                         \r\n");
      out.write("\t\t     $(\"#proimage\").attr(\"src\",pimage2);   \r\n");
      out.write("\t\t     $(\".rcode\").html(rcode);}     \r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("                  });\r\n");
      out.write("              \r\n");
      out.write("                 \t\t        \t\t\r\n");
      out.write("                 \t\t\r\n");
      out.write("                });\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("        \r\n");
      out.write("                               \r\n");
      out.write("        \r\n");
      out.write("            $(\"#btnClose\").on(\"click\",function(){\r\n");
      out.write("                  $(\"#darken-background\").hide();\r\n");
      out.write("               });\r\n");
      out.write("//추가\r\n");
      out.write("\r\n");
      out.write("$(\".reviewDelete\").on(\"click\",function(){\r\n");
      out.write("\r\n");
      out.write("\tvar rcode=$(this).parent().parent().find(\"#here\").find(\".rcode\").text();\r\n");
      out.write("\tvar ccode=$(\".ccode\").val();\r\n");
      out.write("\tif(!confirm(\"정말로 삭제하실건가요?\")) return;\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\ttype:\"post\",\r\n");
      out.write("\t\turl:\"reivewDelete\",\r\n");
      out.write("\t\tdata:{\"rcode\":rcode},\r\n");
      out.write("\t\tsuccess:function(){\r\n");
      out.write("\t\t\talert(\"삭제되었습니다.\");\r\n");
      out.write("\t\t\tlocation.href=\"reply?ccode=\"+ccode;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("})\r\n");
      out.write("\r\n");
      out.write("$(\".reviewUpdate\").on(\"click\",function(){\r\n");
      out.write("\tvar ccode=$(\".ccode\").val();\r\n");
      out.write("\tvar rcode=$(this).parent().parent().find(\"#here\").find(\".rcode\").text();\r\n");
      out.write("\t\r\n");
      out.write("\tlocation.href=\"reviewUpdate?rcode=\"+rcode+\"&ccode=\"+ccode;\r\n");
      out.write("\t\r\n");
      out.write("})\r\n");
      out.write("$(\"#image\").dblclick(function(){\r\n");
      out.write("    $(\".btnGood\").click();\r\n");
      out.write("});\r\n");
      out.write("goodCount();\r\n");
      out.write("function goodCount(){\r\n");
      out.write("\t$(\".single-instagram\").on(\"click\",function(){\r\n");
      out.write("\t\tvar rcode=$(this).children(\".rcode\").val();\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype:\"get\",\r\n");
      out.write("\t\t\turl:\"goodCount\",\r\n");
      out.write("\t\t\tdata:{\"rcode\":rcode},\r\n");
      out.write("\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\tvar goodX=\"\";\r\n");
      out.write("\t\t\t\tvar goodO=\"\";\r\n");
      out.write("\t\t\t\tif(data.userGood!=null){\r\n");
      out.write("\t\t\t\t\tif(data.userGood==1){\r\n");
      out.write("\t\t\t\t\t\tgoodO += \"<img style='width:15px;height:15px;' src='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/core-img/heart_color.png'>\";\r\n");
      out.write("\t\t\t\t\t\tgoodO += \"&nbsp;좋아요&nbsp;\";\r\n");
      out.write("\t\t\t\t\t\t$(\".btnGood\").html(goodO+data.goodCount+\"개\");\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\tgoodX += \"<img style='width:15px;height:15px;' src='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/core-img/heart_no.png'>\";\r\n");
      out.write("\t\t\t\t\t\tgoodX += \"&nbsp;좋아요&nbsp;\";\r\n");
      out.write("\t\t\t\t\t\t$(\".btnGood\").html(goodX+data.goodCount+\"개\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\tgoodX += \"<img style='width:15px;height:15px;' src='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/core-img/heart_no.png'>\";\r\n");
      out.write("\t\t\t\t\tgoodX += \"&nbsp;좋아요&nbsp;\";\r\n");
      out.write("\t\t\t\t\t$(\".btnGood\").html(goodX+data.goodCount+\"개\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("};\r\n");
      out.write("$(\".btnGood\").on(\"click\",function(){\r\n");
      out.write("\tvar ccode=$(\".ccode\").val();\r\n");
      out.write("\tvar rcode=$(this).parent().parent().find(\"#here\").find(\".rcode\").text();\r\n");
      out.write("\tvar isLogin ='");
      out.print(session.getAttribute("gid"));
      out.write("' == 'null' ? false: true;\r\n");
      out.write("\tif(isLogin){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype:\"post\",\r\n");
      out.write("\t\t\turl:\"good\",\r\n");
      out.write("\t\t\tdata:{\"rcode\":rcode},\r\n");
      out.write("\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(data==1){\r\n");
      out.write("\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\ttype:\"get\",\r\n");
      out.write("\t\t\t\t\t\turl:\"goodCount\",\r\n");
      out.write("\t\t\t\t\t\tdata:{\"rcode\":rcode},\r\n");
      out.write("\t\t\t\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\tvar goodX=\"\";\r\n");
      out.write("\t\t\t\t\t\t\tvar goodO=\"\";\r\n");
      out.write("\t\t\t\t\t\t\tif(data.userGood!=null){\r\n");
      out.write("\t\t\t\t\t\t\t\tif(data.userGood==1){\r\n");
      out.write("\t\t\t\t\t\t\t\t\tgoodO += \"<img style='width:15px;height:15px;' src='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/core-img/heart_color.png'>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\tgoodO += \"&nbsp;좋아요&nbsp;\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\".btnGood\").html(goodO+data.goodCount+\"개\");\r\n");
      out.write("\t\t\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t\t\tgoodX += \"<img style='width:15px;height:15px;' src='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/core-img/heart_no.png'>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\tgoodX += \"&nbsp;좋아요&nbsp;\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\".btnGood\").html(goodX+data.goodCount+\"개\");\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t\tgoodX += \"<img style='width:15px;height:15px;' src='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/core-img/heart_no.png'>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tgoodX += \"&nbsp;좋아요&nbsp;\";\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\".btnGood\").html(goodX+data.goodCount+\"개\");\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\ttype:\"get\",\r\n");
      out.write("\t\t\t\t\t\turl:\"goodCount\",\r\n");
      out.write("\t\t\t\t\t\tdata:{\"rcode\":rcode},\r\n");
      out.write("\t\t\t\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\t\t\t\tvar goodX=\"\";\r\n");
      out.write("\t\t\t\t\t\t\tvar goodO=\"\";\r\n");
      out.write("\t\t\t\t\t\t\tif(data.userGood!=null){\r\n");
      out.write("\t\t\t\t\t\t\t\tif(data.userGood==1){\r\n");
      out.write("\t\t\t\t\t\t\t\t\tgoodO += \"<img style='width:15px;height:15px;' src='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/core-img/heart_color.png'>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\tgoodO += \"&nbsp;좋아요&nbsp;\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\".btnGood\").html(goodO+data.goodCount+\"개\");\r\n");
      out.write("\t\t\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t\t\tgoodX += \"<img style='width:15px;height:15px;' src='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/core-img/heart_no.png'>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\tgoodX += \"&nbsp;좋아요&nbsp;\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\".btnGood\").html(goodX+data.goodCount+\"개\");\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t\tgoodX += \"<img style='width:15px;height:15px;' src='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/core-img/heart_no.png'>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tgoodX += \"&nbsp;좋아요&nbsp;\";\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\".btnGood\").html(goodX+data.goodCount+\"개\");\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\talert(\"로그인이 필요합니다.\");\r\n");
      out.write("\t\tlocation.href=\"good1?ccode=\"+ccode;\r\n");
      out.write("\t}\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f0.setParent(null);
    // /WEB-INF/views/reply.jsp(17,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setVar("path");
    // /WEB-INF/views/reply.jsp(17,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/reply.jsp(17,0) '${pageContext.request.contextPath}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
    if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /WEB-INF/views/reply.jsp(110,7) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/reply.jsp(110,7) '${reviewlist}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${reviewlist}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /WEB-INF/views/reply.jsp(110,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("vo");
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("       \r\n");
          out.write("      <!-- Single Instagram -->\r\n");
          out.write("      <div class=\"single-instagram\" style=\"margin-right: 70px; margin-top: 70px; float:left;\">\r\n");
          out.write("         <img src=\"display?fileName=attach/");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.rimage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" alt=\"\" style=\"width:300px; height:300px\" >\r\n");
          out.write("         <input type=\"hidden\" class=\"content\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.rcontent}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" >\r\n");
          out.write("         <input type=\"hidden\" class=\"nick\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.gid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" >\r\n");
          out.write("         <div class=\"pimage\"><img src=\"display?fileName=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.gimage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"></div>\r\n");
          out.write("         <input type=\"hidden\" class=\"rcode\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.rcode}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" >\r\n");
          out.write("         <input type=\"hidden\" class=\"ccode\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.ccode}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("         <!-- Image Zoom -->\r\n");
          out.write("     \r\n");
          out.write("      </div>\r\n");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }
}
