/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-12-26 13:49:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class reviewInsert_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/spring/final1/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/final11/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1604883833700L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("    <style>\r\n");
      out.write("    #listFile img{width:89px;height:89px;float:left;margin:5px;}\r\n");
      out.write("    #btnImage{margin:5px;float:left;width: 89px;height: 89px;line-height:89px;text-align:center;border: 1px dashed #DBDBDB;cursor: pointer;opacity: 1;transform: scale(1);}\r\n");
      out.write("     #star_grade a{\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        color: gray;\r\n");
      out.write("    }\r\n");
      out.write("    #star_grade a.on{\r\n");
      out.write("        color: red;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("    <!-- The above 4 meta tags *must* come first in the head; any other head content must come *after* these tags -->\r\n");
      out.write("\r\n");
      out.write("      <!-- Title -->\r\n");
      out.write("      <title>Cafe人 - 카페를 좋아하는 사람들</title>\r\n");
      out.write(" ");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    <!-- Favicon -->\r\n");
      out.write("    <link rel=\"icon\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/core-img/favicon2.png.jpg\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Stylesheet -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/style.css\">\r\n");
      out.write("    <script src=\"https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-3.1.1.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- Preloader -->\r\n");
      out.write("    <div class=\"preloader d-flex align-items-center justify-content-center\">\r\n");
      out.write("        <div class=\"preloader-content\">\r\n");
      out.write("            <h3>Welecome Caffe人</h3>\r\n");
      out.write("            <div id=\"cooking\">\r\n");
      out.write("                <div class=\"bubble\"></div>\r\n");
      out.write("                <div class=\"bubble\"></div>\r\n");
      out.write("                <div class=\"bubble\"></div>\r\n");
      out.write("                <div class=\"bubble\"></div>\r\n");
      out.write("                <div class=\"bubble\"></div>\r\n");
      out.write("                <div id=\"area\">\r\n");
      out.write("                    <div id=\"sides\">\r\n");
      out.write("                        <div id=\"pan\"></div>\r\n");
      out.write("                        <div id=\"handle\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div id=\"pancake\">\r\n");
      out.write("                        <div id=\"pastry\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "secmenu.jsp", out, false);
      out.write("\r\n");
      out.write("  \r\n");
      out.write("<div style=\"margin:0 auto;text-align:center;margin-top:40px;\"><strong style=\"font-size:28px;#EC7777\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.cname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</strong><span style=\"font-size:16px;\">&nbsp;에대한 솔직한 리뷰를 작성해주세요.</span></div>\r\n");
      out.write("\r\n");
      out.write("\t<form name=\"frm\" action=\"reviewInsert\" method=\"post\"\r\n");
      out.write("\t\tenctype=\"multipart/form-data\">\r\n");
      out.write("\t\t<div style=\"width:678px;height:591px;margin:0 auto;text-align:center;padding: 16px;\">\r\n");
      out.write("\t\t<div style=\"border:1px solid gray;margin:10px;padding:10px;\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"ccode\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.ccode}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"gid\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${gmember.gid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"rscope\" value=\"0\">\r\n");
      out.write("\t\t\t<p id=\"star_grade\">\r\n");
      out.write("       \t \t\t<a href=\"#\" style=\"font-size:30px;\">★</a>\r\n");
      out.write("        \t\t<a href=\"#\" style=\"font-size:30px;\">★</a>\r\n");
      out.write("        \t\t<a href=\"#\" style=\"font-size:30px;\">★</a>\r\n");
      out.write("        \t\t<a href=\"#\" style=\"font-size:30px;\">★</a>\r\n");
      out.write("        \t\t<a href=\"#\" style=\"font-size:30px;\">★</a>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<textarea maxlength=\"10000\" name=\"rcontent\" placeholder=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${gmember.gnickname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" 님, 주문하신 메뉴는 어떠셨나요? 카페의 분위기와 서비스도 궁금해요!\" style=\"border: 0;resize: none;margin:10px auto;width:100%;overflow: hidden; overflow-wrap: break-word; height: 150px;padding:10px;\"></textarea> \r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<div id = \"listFile\" style=\"overflow:hidden;margin:5px;\">\r\n");
      out.write("\t\t\t<input type = button id = \"btnImage\" value = \"+\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<input type=\"file\" name=\"files\" style=\"display:none\" multiple>\r\n");
      out.write("\t\t\t<input type = \"submit\" value = \"리뷰 등록\" style=\"float:right;min-width: 140px;min-height: 50px;padding-left: 14px;padding-right: 14px;border: 1px solid #ff7100;border-radius: 50px;font-size: 16px;color: #FFFFFF;text-align: center;background-color: #EC7777;margin-right:5px;appearance: none;cursor: pointer;\">\r\n");
      out.write("\t\t\t<input type = \"reset\" value = \"취소\" style=\"float:right;    min-width: 140px;min-height: 50px;margin-right: 16px;padding-left: 14px;padding-right: 14px;border: 1px solid #7F7F7F;border-radius: 50px;font-size: 16px;color: #7F7F7F;text-align: center;background-color: #FFFFFF;\" onClick=\"location.href='read?ccode=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.ccode}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("    <!-- ##### Footer Area Start ##### -->\r\n");
      out.write("    <footer class=\"footer-area\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-12 col-sm-5\">\r\n");
      out.write("                    <!-- Copywrite Text -->\r\n");
      out.write("                    <p class=\"copywrite-text\"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class=\"fa fa-heart-o\" aria-hidden=\"true\"></i> by <a href=\"https://colorlib.com\" target=\"_blank\">Colorlib</a>\r\n");
      out.write("<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-12 col-sm-7\">\r\n");
      out.write("                    <!-- Footer Nav -->\r\n");
      out.write("                    <div class=\"footer-nav\">\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li class=\"active\"><a href=\"#\">Home</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Recipes</a></li>\r\n");
      out.write("                            <li><a href=\"#\">About Us</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Blog</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Contact</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("    <!-- ##### Footer Area Start ##### -->\r\n");
      out.write("\r\n");
      out.write("    <!-- ##### All Javascript Script ##### -->\r\n");
      out.write("    <!-- jQuery-2.2.4 js -->\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery/jquery-2.2.4.min.js\"></script>\r\n");
      out.write("    <!-- Popper js -->\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/bootstrap/popper.min.js\"></script>\r\n");
      out.write("    <!-- Bootstrap js -->\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/bootstrap/bootstrap.min.js\"></script>\r\n");
      out.write("    <!-- All Plugins js -->\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/plugins/plugins.js\"></script>\r\n");
      out.write("    <!-- Active js -->\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/active.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("$('#star_grade a').click(function(){\r\n");
      out.write("    $(this).parent().children(\"a\").removeClass(\"on\");  /* 별점의 on 클래스 전부 제거 */ \r\n");
      out.write("    $(this).addClass(\"on\").prevAll(\"a\").addClass(\"on\"); /* 클릭한 별과, 그 앞 까지 별점에 on 클래스 추가 */\r\n");
      out.write("    var scope=$(\".on\").length;\r\n");
      out.write("   \r\n");
      out.write("    return false;\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\t$(frm).on(\"submit\",function(e){\r\n");
      out.write("\t\te.preventDefault();\r\n");
      out.write("\t\tvar scope=$(\".on\").length;\r\n");
      out.write("\t  \r\n");
      out.write("\t    $(frm.rscope).val(scope);\r\n");
      out.write("\t\tif(!confirm(\"등록 하시겠습니까?\")) return;\r\n");
      out.write("\t\tfrm.submit();\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#btnImage\").on(\"click\",function(){\r\n");
      out.write("\t\t$(frm.files).click();\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(frm.files).on(\"change\",function(){\r\n");
      out.write("\t\tvar files = $(frm.files)[0].files;\r\n");
      out.write("\t\tvar str=\"\";\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.each(files,function(index, file){\r\n");
      out.write("\t\t\tstr += \"<img src='\"+URL.createObjectURL(file)+\"'>\";\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\"#listFile\").html(str+\"<input type = button id = 'btnImage' value = '+' >\");\t\r\n");
      out.write("\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f0.setParent(null);
    // /WEB-INF/views/reviewInsert.jsp(27,1) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setVar("path");
    // /WEB-INF/views/reviewInsert.jsp(27,1) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/reviewInsert.jsp(27,1) '${pageContext.request.contextPath}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
    if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
    return false;
  }
}
